#!/bin/bash

# strict mode so script quits immediately upon failure
set -eo pipefail

dataDir=$1 ## Directory that contains GENERAL and PROTECTED folders
containerDataDir=$2 ## Directory that contains data generated by dpdash

singularity exec -B ${containerDataDir}:/data -B ${dataDir}:${dataDir} dpdash2.img /data/scripts/push.sh
