Bootstrap:docker
From:centos:7.4.1708


%labels
    AUTHOR jisoolily_jeong@harvard.edu
    AUTHOR timothy_okeefe@harvard.edu
    AUTHOR hhoke@fas.harvard.edu

    AUTHOR and MAINTAINER tbillah@bwh.harvard.edu


%post
    ## Set data path
    mkdir -p /sw/apps/
    mkdir -p /data/dpdash/
    cd /sw/apps/


    ## update yum and install some useful things
    yum -y update
    yum -y groupinstall "Development tools"
    yum -y install epel-release
    yum -y install net-tools telnet wget git tar which \
        bzip2 p7zip vim vi cronie sudo


    ## install the RabbitMQ message queue
    wget https://github.com/rabbitmq/erlang-rpm/releases/download/v19.3.6.13/erlang-19.3.6.13-1.el7.centos.x86_64.rpm
    yum -y install erlang-19.3.6.13-1.el7.centos.x86_64.rpm
    wget https://github.com/rabbitmq/rabbitmq-server/releases/download/rabbitmq_v3_6_9/rabbitmq-server-3.6.9-1.el6.noarch.rpm
    rpm --import https://www.rabbitmq.com/rabbitmq-signing-key-public.asc
    yum -y install rabbitmq-server-3.6.9-1.el6.noarch.rpm


    ## install miniconda3
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O Miniconda3-latest-Linux-x86_64.sh
    /bin/bash Miniconda3-latest-Linux-x86_64.sh -b -p miniconda3/
    source miniconda3/bin/activate

    ## install the Node.js run-time
    curl --silent --location https://rpm.nodesource.com/setup_16.x | bash -
    yum -y install nodejs

    ## install the MongoDB document database
    echo -e "[mongodb-org-4.4]
name=MongoDB Repository
baseurl=https://repo.mongodb.org/yum/redhat/7/mongodb-org/4.4/x86_64/
gpgcheck=1
enabled=1
gpgkey=https://www.mongodb.org/static/pgp/server-4.4.asc" >> /etc/yum.repos.d/mongodb-org-4.4.repo

    yum -y install mongodb-org


    ## install the Celery asyncronous task queue
    pip install "celery==4.3.0" "vine<5.0.0"


    ## clone the DPdash digital phenotyping dashboard
    git clone https://github.com/PREDICT-DPACC/dpdash.git
    cd dpdash
    mkdir app_build
    ## use version of node found in .nvmrc
    npm install -g n
    n auto
    export PATH=/usr/local/bin/node:$PATH

    ## use latest version of npm
    npm install -g npm@latest

    ## install DPdash dependencies
    npm install --legacy-peer-deps
    npm run transpile
    npm run build


    cd ..

    ## install Supervisord process control system
    pip install supervisor


    ## clear all caches
    yum clean all
    conda clean -y --all
    rm -rf ~/.cache/pip/*

%environment
    ## miniconda3 pnlpipe3
    export PATH=/sw/apps/miniconda3/bin:$PATH
    export PATH=/usr/local/bin/node:$PATH


